/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mx.itson.mvp.view;

/**
 *
 * @author luismorellb
 */
public class POSView extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(POSView.class.getName());

    /**
     * Creates new form POSView
     */
    public javax.swing.table.DefaultTableModel modeloTabla;
    
    public POSView() {
        initComponents();
        
        modeloTabla = new javax.swing.table.DefaultTableModel(
            new Object[]{"Nombre", "Precio", "Cantidad", "Subtotal"}, 0
        );

        tablaProductos.setModel(modeloTabla);
        totalCompra.setEditable(false);

    }
    
    public String getNombre() {
        return productName.getText().trim();
    }

    public String getPrecio() {
        return productoPrecio.getText().trim();
    }

    public String getCantidad() {
        return productoCantidad.getText().trim();
    }

    public void limpiarCampos() {
        productName.setText("");
        productoPrecio.setText("");
        productoCantidad.setText("");
    }

    public void setTotal(double total) {
        totalCompra.setText("$" + String.format("%.2f", total));
    }

    public int getFilaSeleccionada() {
        return tablaProductos.getSelectedRow();
    }

    public void agregarFila(Object[] datos) {
        modeloTabla.addRow(datos);
    }

    public void eliminarFila(int fila) {
        modeloTabla.removeRow(fila);
    }

    public void limpiarTabla() {
        modeloTabla.setRowCount(0);
    }

    public void onAgregar(java.awt.event.ActionListener listener) {
        btnAgregar.addActionListener(listener);
    }

    public void onEliminar(java.awt.event.ActionListener listener) {
        btnEliminar.addActionListener(listener);
    }

    public void onFinalizar(java.awt.event.ActionListener listener) {
        btnFinalizarVenta.addActionListener(listener);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaProductos = new javax.swing.JTable();
        labelProducto = new javax.swing.JLabel();
        productName = new javax.swing.JTextField();
        labelPrecio = new javax.swing.JLabel();
        productoPrecio = new javax.swing.JTextField();
        labelCantidad = new javax.swing.JLabel();
        productoCantidad = new javax.swing.JTextField();
        btnAgregar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnFinalizarVenta = new javax.swing.JButton();
        labelTotal = new javax.swing.JLabel();
        totalCompra = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tablaProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nombre", "Precio", "Cantidad", "Subtotal"
            }
        ));
        jScrollPane1.setViewportView(tablaProductos);

        labelProducto.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelProducto.setText("Producto");

        productName.addActionListener(this::productNameActionPerformed);

        labelPrecio.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelPrecio.setText("Precio");

        productoPrecio.addActionListener(this::productoPrecioActionPerformed);

        labelCantidad.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelCantidad.setText("Cantidad");

        productoCantidad.addActionListener(this::productoCantidadActionPerformed);

        btnAgregar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(this::btnAgregarActionPerformed);

        btnEliminar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(this::btnEliminarActionPerformed);

        btnFinalizarVenta.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnFinalizarVenta.setText("Finalizar Venta");
        btnFinalizarVenta.addActionListener(this::btnFinalizarVentaActionPerformed);

        labelTotal.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        labelTotal.setText("Total a pagar:");

        totalCompra.addActionListener(this::totalCompraActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnEliminar)
                    .addComponent(labelProducto))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(productName, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(labelPrecio))
                    .addComponent(btnFinalizarVenta))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(labelTotal)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(totalCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(productoPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(labelCantidad)
                        .addGap(18, 18, 18)
                        .addComponent(productoCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelProducto)
                    .addComponent(productName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelPrecio)
                    .addComponent(productoPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelCantidad)
                    .addComponent(productoCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAgregar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnEliminar)
                        .addComponent(btnFinalizarVenta))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTotal)
                    .addComponent(totalCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void productNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_productNameActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnFinalizarVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinalizarVentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnFinalizarVentaActionPerformed

    private void totalCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalCompraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalCompraActionPerformed

    private void productoPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productoPrecioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_productoPrecioActionPerformed

    private void productoCantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productoCantidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_productoCantidadActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAgregarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new POSView().setVisible(true));
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnAgregar;
    public javax.swing.JButton btnEliminar;
    public javax.swing.JButton btnFinalizarVenta;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JLabel labelCantidad;
    public javax.swing.JLabel labelPrecio;
    public javax.swing.JLabel labelProducto;
    public javax.swing.JLabel labelTotal;
    public javax.swing.JTextField productName;
    public javax.swing.JTextField productoCantidad;
    public javax.swing.JTextField productoPrecio;
    public javax.swing.JTable tablaProductos;
    public javax.swing.JTextField totalCompra;
    // End of variables declaration//GEN-END:variables
}
